//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorXamarin.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorXamarin.Application.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current count:.
        /// </summary>
        public static string Counter_CurrentCount {
            get {
                return ResourceManager.GetString("Counter_CurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string Counter_Header {
            get {
                return ResourceManager.GetString("Counter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        public static string Counter_Increment {
            get {
                return ResourceManager.GetString("Counter_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balmy.
        /// </summary>
        public static string FetchData__Summary_Balmy {
            get {
                return ResourceManager.GetString("FetchData__Summary_Balmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracing.
        /// </summary>
        public static string FetchData__Summary_Bracing {
            get {
                return ResourceManager.GetString("FetchData__Summary_Bracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilly.
        /// </summary>
        public static string FetchData__Summary_Chilly {
            get {
                return ResourceManager.GetString("FetchData__Summary_Chilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        public static string FetchData__Summary_Cool {
            get {
                return ResourceManager.GetString("FetchData__Summary_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing.
        /// </summary>
        public static string FetchData__Summary_Freezing {
            get {
                return ResourceManager.GetString("FetchData__Summary_Freezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string FetchData__Summary_Hot {
            get {
                return ResourceManager.GetString("FetchData__Summary_Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mild.
        /// </summary>
        public static string FetchData__Summary_Mild {
            get {
                return ResourceManager.GetString("FetchData__Summary_Mild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorching.
        /// </summary>
        public static string FetchData__Summary_Scorching {
            get {
                return ResourceManager.GetString("FetchData__Summary_Scorching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweltering.
        /// </summary>
        public static string FetchData__Summary_Sweltering {
            get {
                return ResourceManager.GetString("FetchData__Summary_Sweltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        public static string FetchData__Summary_Warm {
            get {
                return ResourceManager.GetString("FetchData__Summary_Warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component demonstrates fetching data from the server..
        /// </summary>
        public static string FetchData_Description {
            get {
                return ResourceManager.GetString("FetchData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string FetchData_Header {
            get {
                return ResourceManager.GetString("FetchData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FetchData_Header_Date {
            get {
                return ResourceManager.GetString("FetchData_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string FetchData_Header_Summary {
            get {
                return ResourceManager.GetString("FetchData_Header_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (C).
        /// </summary>
        public static string FetchData_Header_TempC {
            get {
                return ResourceManager.GetString("FetchData_Header_TempC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (F).
        /// </summary>
        public static string FetchData_Header_TempF {
            get {
                return ResourceManager.GetString("FetchData_Header_TempF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string FetchData_Loading {
            get {
                return ResourceManager.GetString("FetchData_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        public static string Home_Header {
            get {
                return ResourceManager.GetString("Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is Blazor working for you?.
        /// </summary>
        public static string Home_SurveyTitle {
            get {
                return ResourceManager.GetString("Home_SurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new app..
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlazorXamarin.Blazor.
        /// </summary>
        public static string NavMenu_AppName {
            get {
                return ResourceManager.GetString("NavMenu_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string NavMenu_Counter {
            get {
                return ResourceManager.GetString("NavMenu_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch data.
        /// </summary>
        public static string NavMenu_FetchData {
            get {
                return ResourceManager.GetString("NavMenu_FetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavMenu_Home {
            get {
                return ResourceManager.GetString("NavMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brief survey.
        /// </summary>
        public static string Survey_Anchor {
            get {
                return ResourceManager.GetString("Survey_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and tell us what you think..
        /// </summary>
        public static string Survey_End {
            get {
                return ResourceManager.GetString("Survey_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take our.
        /// </summary>
        public static string Survey_Start {
            get {
                return ResourceManager.GetString("Survey_Start", resourceCulture);
            }
        }
    }
}
